services:
  postgres_db:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: jointravel_db
      POSTGRES_USER: jointravel_user
      POSTGRES_PASSWORD: jointravel_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    container_name: jointravel-back-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_HOST_PORT}:8080"
    environment:
      - POSTGRES_DB=jointravel_db
      - POSTGRES_USER=jointravel_user
      - POSTGRES_PASSWORD=jointravel_password
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    depends_on:
      - postgres_db

volumes:
  postgres_data:
