services:
  backend:
    container_name: jointravel-back-container
    image: jointravel-back
    build:
      context: .
      args:
    ports:
      - "${APP_HOST_PORT}:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
