services:
  postgres_db:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: jointravel_db
      POSTGRES_USER: jointravel_user
      POSTGRES_PASSWORD: jointravel_password
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    container_name: jointravel-back-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${APP_HOST_PORT}:8080"
    environment:
      - POSTGRES_DB=jointravel_db
      - POSTGRES_USER=jointravel_user
      - POSTGRES_PASSWORD=jointravel_password
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
      - TZ=UTC
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./pnpm-lock.yaml:/usr/src/app/pnpm-lock.yaml
      - uploads_data:/usr/src/app/uploads
    depends_on:
      - postgres_db

volumes:
  postgres_data:
  uploads_data:
    driver: local
