version: '3.8'

services:
  backend:
    container_name: jointravel-back-container
    image: jointravel-back
    build:
      context: .
      args:
        - POSTGRESQL_CONN=${POSTGRESQL_CONN}
    ports:
      - "${APP_HOST_PORT}:8080"
    restart: unless-stopped
    environment:
      - POSTGRESQL_CONN=${POSTGRESQL_CONN}
